{
 "title": "SystemD Services Information",
 "description": "SystemD services status dashboard for the Srvinfo script",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "influxdb" },
   {
    "name": "host",
    "query": "SHOW TAG VALUES WITH KEY = \"host\""
   },
   {
    "name": "service",
    "query": "SHOW TAG VALUES WITH KEY = \"service\""
   }
  ]
 },
 "panels": [
  { "title": "Global Services Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "MONITORED HOSTS",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "1h" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" }
     ],
     "measurement": "services_stats",
     "query": "SHOW TAG VALUES FROM \"services_stats\" WITH KEY = \"host\" WHERE (\"host\" =~ /^$host$/)",
     "select": [
      [
       { "params": [ "status" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "Global Availability",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT count(\"status\") * 100 / sum(\"status\")   FROM \"services_stats\" WHERE (\"host\" =~ /^$host$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "CURRENT ALERT(S)",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "processes_processes",
     "query": "SELECT count(\"status\") FROM \"services_stats\" WHERE (\"host\" =~ /^$host$/) AND \"status\" = 0 AND $timeFilter GROUP BY time(2m) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "min"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "instance", "operator": "=~", "value": "/^$instance$/" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "ps_count" }
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT count(\"status\") FROM \"services_stats\" WHERE (\"host\" =~ /^$host$/) AND \"status\" = 3 AND $timeFilter GROUP BY time(2m) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT count(\"status\") FROM \"services_stats\" WHERE (\"host\" =~ /^$host$/) AND \"status\" = 4 AND $timeFilter GROUP BY time(2m) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "CURRENT OK",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT count(\"status\") FROM \"services_stats\" WHERE (\"host\" =~ /^$host$/) AND \"status\" = 1 AND $timeFilter GROUP BY time(2m)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "STATUSES LOGS",
   "type": "table",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "service" ], "type": "tag" }
     ],
     "measurement": "services_stats",
     "query": "SELECT count(\"status\") FROM \"services_stats\" WHERE (\"host\" =~ /^$host$/ AND \"service\" =~ /^$service$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "status" ], "type": "field" },
       { "params": [ "Status" ], "type": "alias" }
      ],
      [
       { "params": [ "status_time" ], "type": "field" },
       { "params": [ "Since" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "service", "operator": "=~", "value": "/^$service$/" }
     ]
    }
   ]
  },
  {
   "title": "MONITORED SERVICES",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "1h" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" }
     ],
     "measurement": "services_stats",
     "query": "SHOW TAG VALUES FROM \"services_stats\" WITH KEY = \"service\" WHERE (\"host\" =~ /^$host$/)\n",
     "select": [
      [
       { "params": [ "status" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "SERVICES STATUS",
   "type": "yesoreyeram-boomtable-panel",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {
     "alias": "status:$tag_host:$tag_service",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "service" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "services_stats",
     "query": "SELECT mean(\"status\") FROM \"services_stats\" WHERE (\"host\" =~ /^$host$/ AND \"service\" =~ /^$service$/) AND $timeFilter GROUP BY time($__interval), \"host\", \"service\" fill(null)",
     "select": [
      [
       { "params": [ "status" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "service", "operator": "=~", "value": "/^$service$/" }
     ]
    }
   ]
  },
  {
   "title": "SERVICES STATUS IN TIME",
   "type": "flant-statusmap-panel",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 14 },
   "targets": [
    {
     "alias": "$tag_host:$tag_service",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "service" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "services_stats",
     "query": "SELECT mean(\"status\") FROM \"services_stats\" WHERE (\"host\" =~ /^$host$/ AND \"service\" =~ /^$service$/) AND $timeFilter GROUP BY time($__interval), \"host\", \"service\" fill(null)",
     "select": [
      [
       { "params": [ "status" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "service", "operator": "=~", "value": "/^$service$/" }
     ]
    }
   ]
  }
 ]
}